services:
  backend:
    image: docker.illegalesachen.download/osu/music/proxy:latest
    container_name: proxy-container
    environment:
      - CLIENT_ID=34597
      - CLIENT_SECRET=WwTSsGxrpZeTakYHl4eGFQjVK1zgfUKvvkPvU1DO
      - REDIRECT_URI=/callback
    ports:
      - "5002:80"
    volumes:
      - ./data:/app/data
    restart: always
    depends_on:
      - frontend

  frontend:
    image: docker.illegalesachen.download/osu/music/frontend:latest
    container_name: frontend-container
    ports:
      - "5001:80"
    restart: always