apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: horsa-dev
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: horsa-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
        - name: backend
          image: "docker.illegalesachen.download/horsa-backend:1037c21db50619e27e0bbca3e29ce2178b86d84d"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgres://user:password@postgres:5432/horsea_db?sslmode=disable"
            - name: JWT_SECRET
              value: "random_ass_secret"
            - name: ENV
              value: "development"
            - name: ACCOUNT_ID
              value: "80a1c5d4ec18d522a4c68055fde16999"
            - name: ACCESS_KEY
              value: "2419f09a43c30484c9b2c6ac5dd63a2e"
            - name: SECRET_KEY
              value: "e3ef2da9a650da251b449fd619b12edae90e533c2a48272eb82f1f40861998ec"
            - name: BUCKET
              value: "horsa"
            - name: KEYCLOAK_URL
              value: "https://sso.illegalesachen.download"
            - name: KEYCLOAK_REALM
              value: "horsa"
            - name: KEYCLOAK_CLIENT_ID
              value: "capability-client"
            - name: KEYCLOAK_CLIENT_SECRET
              value: kbgQ5WnMu67GDfpQ7Cvo6Uflq7x2n1ve
