apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileclap-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: fileclap-container
          env:
            - name: ENVIRONMENT
              value: "prod"
          resources:
            requests:
              cpu: "2"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "1Gi"