apiVersion: v1
kind: Service
metadata:
  name: thumbnail-service
spec:
  type: NodePort
  selector:
    app: thumbnail-app
  ports:
    - name: grpc-port
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: http-gateway
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30502
