apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tweeter-ingress
  namespace: ise-tweeter
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: ise-tweeter-strip-api-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: ise-tweeter.illegalesachen.download
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: tweeter-auth-service
                port:
                  number: 80
          - path: /api/tweet
            pathType: Prefix
            backend:
              service:
                name: tweeter-tweet-service
                port:
                  number: 80
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: tweeter-user-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tweeter-frontend-service
                port:
                  number: 80
