apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweeter-user
  namespace: ise-tweeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweeter-user
  template:
    metadata:
      labels:
        app: tweeter-user
    spec:
      containers:
        - name: tweeter-user
          image: docker.illegalesachen.download/uni/ise/user:latest
      imagePullSecrets:
        - name: my-registry-secret
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://tweeter-postgres-db-service:5432/tweeter"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_DATA_REDIS_URL
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              value: "redis"
            - name: BLOB_ENABLED
              value: "true"
            - name: BLOB_CONTAINER
              value: "tweeter"
            - name: BLOB_CONNECTION_STRING
              value: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://tweeter-azurite-service:10000/devstoreaccount1;"
---
apiVersion: v1
kind: Service
metadata:
  name: tweeter-user-service
  namespace: ise-tweeter
spec:
  selector:
    app: tweeter-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  clusterIP: None
